### ISSUE TITLE
Error when running: "UnnaturalScrollWheels.app” will damage your computer. You should move it to the Trash.

### ISSUE THREAD

**Issue by wakedeer** [ther0n/UnnaturalScrollWheels#12] opened 2021-01-10 16:09 UTC
When UnnaturalScrollWheels starts I have warning "UnnaturalScrollWheels.app” will damage your computer. You should move it to the Bin." and only two option: Move to Bin and Cancel. I've set accessibility permissions in settings.
![image](https://user-images.githubusercontent.com/17357740/104128085-95d5df80-5376-11eb-8744-626cfd032458.png)
![image](https://user-images.githubusercontent.com/17357740/104128185-201e4380-5377-11eb-8de5-9d69b98b5e6a.png)

**Comment by ther0n** [comment] 2021-01-10 17:43
Hmmmm. This is a difficult issue to figure out... It obviously works fine on my machine but I'm not sure how to investigate an issue like this since anything I build on my machine will of course be marked as trusted. I'm thinking I may have screwed one of a build options up when I was figuring out how to build the universal binary. I'm going to see if I can get a VM up and running to see if I can reproduce the issue. I notice that you used Brew in your screenshot, what happens when you download the .dmg file directly?

**Comment by mb35534** [comment] 2021-01-10 18:15
I had the same issue. When I downloaded the latest 1.1.1 .dmg directly, I get the following warning: 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/7043299/104131631-1546bd00-533d-11eb-8197-f9e9831a80d9.png">

If I right click the application in finder and click open, I can get it to work properly.

**Comment by ther0n** [comment] 2021-01-10 18:36
> I had the same issue. When I downloaded the latest 1.1.1 .dmg directly, I get the following warning:
> <img alt="image" width="250" src="https://user-images.githubusercontent.com/7043299/104131631-1546bd00-533d-11eb-8197-f9e9831a80d9.png">
> 
> If I right click the application in finder and click open, I can get it to work properly.

@mb35534 This is a different issue and this is expected behavior. To prevent this notice from appearing I would need to pay $100 a year to join the Apple Developer program and get the [app notarized](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution). I'm giving away an app for free so it just doesn't make a lot of sense for me to pay that $100 a year, I could put the app on the App Store for a small fee but it's hard to know if Apple would approve it and if I would be able to break even, given the app is available for free anyway (which I don't want to change).

**Comment by Ale-ri** [comment] 2021-01-10 18:39
I have encountered the same thing as original poster (malware warning, not having permission to run) on version 1.1.0 just this morning. Version 1.1.1 doesn’t give this error, but also doesn’t run. I'm on Big Sur 11.1, Intel based Mac

**Comment by mb35534** [comment] 2021-01-10 18:47
@ther0n Ah, yes, that's different then—I was conflating the two issues. I do really appreciate you making this app free! Just FYI, I did have the same issue as the original poster (could not start the application on Big Sur 11.1 with version 1.1.0 of Unnatural Scroll Wheels).

**Comment by rshaul** [comment] 2021-01-10 21:10
Same problem as OP. Gotta love Apple telling me what software I'm allowed to run. Think it's time to leave this ecosystem.

**Comment by ikai2** [comment] 2021-01-10 21:49
> I had the same issue. When I downloaded the latest 1.1.1 .dmg directly, I get the following warning:
> <img alt="image" width="250" src="https://user-images.githubusercontent.com/7043299/104131631-1546bd00-533d-11eb-8197-f9e9831a80d9.png">
> 
> If I right click the application in finder and click open, I can get it to work properly.

this is easy to fix. Just Right Click again and you will get a new pop up with open (and the app will open normally)

**Comment by ther0n** [comment] 2021-01-11 00:31
I'm not sure what's going on with the 1.1.0 release. Homebrew installs 1.1.0 still but the release I made yesterday doesn't have the issue (1.1.1). If you are having this issue please install the latest release manually.

I'm not the one who added the app to Homebrew cask so I'm not familiar with the process with how to update it to the new version.

**Comment by vhn** [comment] 2021-01-11 01:59
Looks like their cli can help with version updates:
https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

I ran it and created this:
https://github.com/Homebrew/homebrew-cask/pull/97921

And some feedback for this issue:
Manually installed version 1.1.1 runs perfectly on big sur 11.1, m1 air.

**Comment by AKlaus** [comment] 2021-01-11 07:19
Nope, upgrade to v1.1.1 doesn't work. 
I had v1.1.0 installed manually when noticed the problem after a MacOS update. Updating to 1.1.1 manually didn't bring any joy. 
Uninstalling and installing via homebrew didn't change much. Now on launching `UnnaturalScrollWheels` I don't get any notifications - it just doesn't work....

System: `Big Sur v11.1 `(up-to-date)

**Comment by xavier-niu** [comment] 2021-01-11 07:34
Yes, I have noticed this issue either. I have tried to right-click open but no luck here. Although there isn't any warning, the app would not run properly as well.

Hardware: Intel based mac
System: macOS Big Sur 11.0.1
App Version: 1.1.1

**Comment by bachrc** [comment] 2021-01-11 08:27
I bump this too : The app doesn't start anymore, and I have zero message. Even after reinstalling it.

**Comment by bachrc** [comment] 2021-01-11 08:33
Ok, somehow I made it work :
I went in Security and Privacy settings, in Accessibility : I unchecked UnnaturalScrollWheels, and checked again. And the app launched again.

**Comment by hippwn** [comment] 2021-01-11 09:14
> Ok, somehow I made it work :
> I went in Security and Privacy settings, in Accessibility : I unchecked UnnaturalScrollWheels, and checked again. And the app launched again.

I can confirm it works on intel-based Mac with Big Sur 11.1 and UnnaturalScrollWheels v1.1.1. Thanks buddy!

**Comment by deanc** [comment] 2021-01-11 15:45
> Ok, somehow I made it work :
> I went in Security and Privacy settings, in Accessibility : I unchecked UnnaturalScrollWheels, and checked again. And the app launched again.

This solution did not work for me. System: MacBook Pro (15-inch, 2019), 2,4 GHz 8-Core Intel Core i9

**Comment by ther0n** [comment] 2021-01-11 16:08
@deanc Are you using the latest version 1.1.1?

**Comment by deanc** [comment] 2021-01-11 16:14
@ther0n I am now, and tried the solution but it did not work.

**Comment by ther0n** [comment] 2021-01-11 17:13
## Fix
1. Open System Preferences > Security & Privacy > Privacy > Accessibility
2. Click the lock in the lower left and authenticate
3. Select UnnaturalScrollWheels.app from the list on the left and click the '-' button:
<img width="340" alt="Screen Shot 2021-01-11 at 11 31 26 AM" src="https://user-images.githubusercontent.com/5874301/104210340-c2ced480-5400-11eb-8b67-c9bd654c3faf.png">
4. Right click and open version 1.1.1 from the Applications folder, and you should get a prompt to allow UnnaturalScrollWheels to control your computer. Grant it permission, then run the app.

## Cause?
It seems like this all happened right when I built the new version as a universal binary the other day. I wonder if something I did invalidated the code signature of all older versions. I recently started from scratch with my macOS install when I upgraded to Big Sur about a month ago, and am starting from scratch again as I upgraded to an M1 Mac yesterday. When I opened the project a few days ago in order to build the universal binary release I changed the team here in the signing options since it was red:
<img width="400" alt="Screen Shot 2021-01-11 at 9 34 46 AM" src="https://user-images.githubusercontent.com/5874301/104195357-84311e00-53f0-11eb-87d3-189d1ca18e9f.png">

When "archiving" the app to create the release I chose "Developer ID", though I may have chosen "Copy App" with past versions:
<img width="400" alt="Screen Shot 2021-01-11 at 9 38 29 AM" src="https://user-images.githubusercontent.com/5874301/104195694-f4d83a80-53f0-11eb-9c36-bf235b4643c8.png">

This app started as a weekend project to fix an annoyance I had with macOS. I had never done any macOS development before so I'm not familiar with Xcode or code signing and for the most part fiddled until I got things to work. [Apple's documentation](https://help.apple.com/xcode/mac/current/#/dev91fe7130a) tends to assume you are paying the $100 a year fee to join the Developer Program so I largely disregarded it when it came to building the release version.

If anyone who has the know how to answer these questions it would be a great help!:

- Can changing the above options can invalidate code signatures for older versions?
  - If it does, how do I migrate builds over to new macOS installs (the red "Unknown Team" in the first screenshot) without removing the old team and re-adding my "team"?
- What are the "proper" options to choose for someone building an app without being in the Apple Developer Program?

**Comment by chiibis** [comment] 2021-02-01 18:24
For anyone still struggling with this issue:

Had the same problem with macOS Catalina recently.

After installing the latest version and following steps above it still didn't work. But didn't suggest to move it to bin either.

I have additionally go to one more tab: Preferences > Security & Privacy > Privacy > **General**

And press button 'Open anyway' next to 'Allow on... ' as shown on this screenshot:

![image](https://user-images.githubusercontent.com/7037967/106500911-6dec1e80-64d3-11eb-9899-67899a7d2ba3.png)

**Comment by dtaddis** [comment] 2021-09-21 20:04
Had the issue exactly as described above, and I can get it to run by going to Security settings and explicitly allowing it to "Open Anyway" as suggested. Thanks for coding this great utility!

**Comment by ther0n** [comment] 2021-12-04 17:24
Latest release is now notarized so this shouldn't be an issue anymore.

**Closed by ther0n** 2021-12-04 17:24 UTC
