### ISSUE TITLE
Suggestion: Allow the opposite

### ISSUE THREAD

**Issue by deanc** [ther0n/UnnaturalScrollWheels#3] opened 2020-07-28 09:40 UTC
Hi,

My preferred settings are:

- Trackpad: natural
- Mouse: not natural

Unfortunately every time I plug in a monitor (could be a USB mouse) it reverts them. I presume this is the same issue, just the opposite way around :) So it would be good to persist settings using your tool, but in the opposite.

**Comment by ther0n** [comment] 2020-07-28 13:35
Hi @deanc,

I'm not sure if I completely understand what you are asking. UnnaturalScrollWheels assumes that you want content to scroll up when you move your fingers down on trackpads ("natural") but for content to scroll up when moving your finger up on the top of the scroll wheel with mice ("unnatural"). In System Settings the natural scrolling checkbox under trackpad is "linked" to the setting for the mouse. Toggling it in one place toggles it in the other which is confusing but the reason I made the app. 

With UnnaturalScrollWheels running, checking the box to invert vertical scrolling will invert vertical scrolling from whatever you have set in System Settings *only* for mice with physical scroll wheels. To get your preferred settings (assuming there were no misunderstandings) you will need to have "Scroll Direction: Natural" checked for Trackpad/Mouse (remember the two are the "linked", which is confusing), and in UnnaturalScrollWheels preferences you will need to invert vertical scrolling (and horizontal if you want that).

To do the opposite, where moving your fingers down on the trackpad moves the content down ("unnatural") while moving your fingers down on a scroll wheel moves the content up ("natural"), you will need to uncheck "Scroll direction: Natural" in System Settings, and have "Invert vertical(and optionally horizontal) scrolling" checked in UnnaturalScrollWheels settings.

If things are working on both mouse and trackpad as you'd expect before plugging in the monitor but stop once you plug in the monitor, that's probably a separate issue. I'd need more information about how you have things wired so I can see if I can reproduce the issue, otherwise it will be quite a challenge to fix. What kind of mouse is it? Is the mouse connected to the monitor? Is the monitor connected to the computer through Thunderbolt?

Let me know if that helps, and any additional information you can give me about your setup if it didn't. Thanks!

**Comment by deanc** [comment] 2020-07-28 17:34
Hi ther0n. Sorry I had misunderstood what this was a workaround for. The issue that I have (consistently) is that every time I unplug a monitor (could just be USB mouse but the two usually co-incide through a dongle) my settings for trackpad get inverted. Conversely I then fix them, and when I then plug in my mouse it's back to what it was before. I presume this is somewhat related to the issue you are trying to fix here.

Steps to reproduce (in my case) are pretty simple:
- On just the macbook (no ext. monitor or mice at this point) set trackpad scroll direction to "Natural"
- Plug in a usb mouse (via dongle)
- Mouse scroll direction is now "Natural", set it back to "Unnatural"
- Unplug dongle
- Go to trackpad settings, track is now also set to unnatural

**Comment by ther0n** [comment] 2020-07-28 18:09
Ah ok. You did understand correctly and the app does what you want. The two setting for scroll direction for the trackpad is "linked" to the mouse setting. I don't know why Apple decided to design the settings this way, but UnnaturalScrollWheels fixes/works around the issue. Here's what's happening:

> 1. On just the macbook (no ext. monitor or mice at this point) set trackpad scroll direction to "Natural"

- When you set the scroll direction for the trackpad, you are also setting the scroll direction for the mouse without realizing it since either checkbox toggles the option in both locations.

> 2. Plug in a usb mouse (via dongle)

- Nothing changes.

> 3. Mouse scroll direction is now "Natural", set it back to "Unnatural"

- Mouse scroll direction is set to "Natural" because you turned it on for the trackpad in step one.
- When you set it back to "Unnatural" it's also changing the trackpad option.

> 4. Unplug dongle

- Nothing changes.

> 5. Go to trackpad settings, track is now also set to unnatural

- The trackpad option was changed when you set the scroll direction to "Unnatural" in step 3.

UnnaturalScrollWheels makes it so that you can leave "Natural" scrolling on for the trackpad/mouse (since you can't toggle them independently) but will invert scroll events if they come from physical scroll wheels on a mouse.

**Closed** 2020-07-29 13:03 UTC
